# Generated by Django 5.2.8 on 2026-01-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='outfits/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='wardrobe', to='profiles.userprofile')),
            ],
        ),
    ]
