# Generated by Django 6.0.4 on 2026-09-29 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profiles/')),
                ('style', models.CharField(blank=True, choices=[('Streetwear', 'Streetwear'), ('Casual', 'Casual'), ('Formal', 'Formal'), ('Vintage', 'Vintage'), ('Sporty', 'Sporty')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outfits/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('style_genre', models.CharField(blank=True, choices=[('Streetwear', 'Streetwear'), ('Casual', 'Casual'), ('Formal', 'Formal'), ('Vintage', 'Vintage'), ('Sporty', 'Sporty')], max_length=60)),
                ('weather_suitability', models.CharField(blank=True, choices=[('Rainy', 'Rainy'), ('Sunny', 'Sunny'), ('Cold', 'Cold'), ('Windy', 'Windy')], max_length=60)),
                ('sex', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], max_length=10)),
                ('color', models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Beige', 'Beige')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='pages.userprofile')),
                ('saved_by', models.ManyToManyField(blank=True, related_name='wardrobe', to='pages.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
